### ISSUE TITLE
PHP 8.1, Order Accept = Slack says Provisioned; GUI has empty error; MCP has no service

### ISSUE THREAD

**Issue by lsthompson** [mediacontrolpanel/whmcs-onpremise#2]
G'day @TheRealMattLear 

Just checking if you've had any issues on PHP 8.1 and MediaCP latest stable?

Getting a weird one where the WHMCS Slack notification says provisioned, but we just get the default header:

> Order Accept Encountered Problems

No actual error body below that line as usual, even if we turn on log/display errors.

Only error which appears 10 minutes prior is this, which has some frequency:

`[08-Dec-2023 09:35:17 Australia/Sydney] [WHMCS Application] ERROR: Laminas\Diactoros\Exception\InvalidArgumentException: Query string must not include a URI fragment in /home/username/public_html/vendor/laminas/laminas-diactoros/src/Uri.php:406 Stack trace: #0 /home/username/public_html/vendor/laminas/laminas-diactoros/src/functions/marshal_uri_from_sapi.php(223): Laminas\Diactoros\Uri->withQuery('g=g&amp;m=Door&...') #1 /home/username/public_html/vendor/laminas/laminas-diactoros/src/ServerRequestFactory.php(74): Laminas\Diactoros\marshalUriFromSapi(Array, Array) #2 /home/username/public_html/vendor/whmcs/whmcs-foundation/lib/Http/Message/ServerRequest.php(0): Laminas\Diactoros\ServerRequestFactory::fromGlobals(Array, NULL, NULL, NULL, Array) #3 /home/username/public_html/index.php(0): WHMCS\Http\Message\ServerRequest::fromGlobals() #4 {main} {"exception":"[object] (Laminas\\Diactoros\\Exception\\InvalidArgumentException(code: 0): Query string must not include a URI fragment at /home/username/public_html/vendor/laminas/laminas-diactoros/src/Uri.php:406)"} []`

I wonder if WHMCS 8.7.3 to 8.8.0 may help? They have a history of some dodgy fresh sub-majors.

Else how do you recommend we coax a more helpful failure from Media Control Panel?

Cheers,
Luke

**Comment by TheRealMattLear** [comment]
@lsthompson This error seems unrelated but worth investigating, would recommend opening a ticket with WHMCS regarding that error. We're running PHP 8.1 on our test site and haven't hit any particular issues. Did this occur after upgrading to latest 2.13.7?

I'll request some fresh tests tomorrow and see how it goes.

You can also run an API test at https://www.mediacp.net/tools/apitest/ using one of the presets.

**Comment by lsthompson** [comment]
Cheers @TheRealMattLear - it turns out the error in the Module Queue invoked more questioning:

> An unknown error occurred. To diagnose further, enable module debug logging and try again. 

I've not done that, but had to get the new client up and running, so manually did it.

For the next one, or even a test, we will get the Module Debug Log for you.

**Comment by TheRealMattLear** [comment]
@lsthompson we were unable to replicate any similar problem in our testing. Let me know once you have the debug log entries
